### ISSUE TITLE
missing frontend CSS for new page

### ISSUE THREAD

**Issue by cord** [DigitalCloud/nova-page-tool#2]
great stuff! 

however when creating a new page the CSS seems to be missing?

![nova site 2019-01-23 17-22-09](https://user-images.githubusercontent.com/158588/51620827-7f3ce080-1f33-11e9-9382-7ee1c596d29d.png)

**Comment by devmtm** [comment]
What do you mean by the CSS is missing? Can You explain?

**Comment by devmsh** [comment]
I think @cord  means that the default template must include a CSS to display it in a good design.

**Comment by cord** [comment]
Yes, I would expect some default styling for the standard page elements eg for the hero section both in editor view and in page view
